### ISSUE TITLE
MarkDownload downloads file with incorrect filename

### ISSUE THREAD

**Issue by MercuryOoO** [deathau/markdownload#39] opened 2020-12-23 10:31 UTC
**Chrome**: 87.0.4280.88 (64 bits)
**MarkDownload**: 2.4.1
**OS**: Windows 10 (10.0.19042)
**Issue Ref**: #10 

This issue seems to be related to **Chrome download API** as it **was occurred**( [**Issue 1008884: chrome download API downloads file with incorrect filename**](https://crbug.com/1008884) ) I'm not sure which party should solves this issue first. The same issue appears in different Chrome plugins (such as [**Save Images**](https://github.com/belaviyo/save-images) [Issue ref](https://github.com/belaviyo/save-images/issues/35) ). If this problem cannot be solved temporarily, I hope someone can provide some temporary solutions, thank you!

**Comment by nikiluk** [comment] 2021-01-05 18:31
I confirm the same behavior in the Edge browser. Specifically, when the original title of the page contains `/`, the download splits the title into two, creates a nested structure where the filename has the last part of the title...

For example, when the title is "Coffee and Tea 24/7 restaurant", the resulting path will be
> /Coffee and Tea 24/7 restaurant.md

**Comment by deathau** [comment] 2021-01-06 04:44
@nikiluk, your issue appears to be #40, which I think I have now resolved.

@MercuryOoO I'm pretty sure yours is a duplicate of #10 (but with more info, so I might close #10 as the duplicate).  
It seems to be related to specific _other_ extensions somehow interfering. I know it's a pain, but could you try disabling some other download-related extensions and see if the problem goes away? Just to double check that it is a compatibility issue and there isn't something else going on.

**Comment by nikiluk** [comment] 2021-01-06 07:25
@deathau thank you! I've downloaded the repo to try the update. 
* I like the styling changes you did on options.html
* BUG: for some reason after I attempted to save the webpage extension goes into an endless loop 🔁👀 consuming over 50% of the CPU
* I've also attempted to create a customized Download path but it was not working in all the cases with the last version of the repo.

**Comment by deathau** [comment] 2021-01-06 07:34
@nikiluk yeah, I've got a bit of a WIP in there regarding an attempt to download images relative to the md file which is still buggy. You might have to go back a commit or two to find something stable

**Comment by MercuryOoO** [comment] 2021-01-06 19:36
@deathau **Thanks for your advice**. Although my issue is caused by[ **“Nimbus Screenshot & Screen Video Recorder”**](https://chrome.google.com/webstore/detail/nimbus-screenshot-screen/bpconcjcammlapcogcnnelfmaeghhagj/), it is actually a deeper and more common issue. **Exactly the same issue** has been described clearly in the following places:
- [Filename conflict with "Nimbus Screenshot and Screen Recorder" #423:](https://github.com/gildas-lormeau/SingleFile/issues/423)
- [SingleFile#known-issues](https://github.com/gildas-lormeau/SingleFile#known-issues)
- [Issue 892133: downloading a blob url with chrome.downloads.download fails:](https://bugs.chromium.org/p/chromium/issues/detail?id=892133)
___
Since the issue has been marked as **WontFix** by upstream **Google**, you may close the issue.

**Comment by pinacle2000** [comment] 2021-02-10 14:54
[SingleFile](https://github.com/gildas-lormeau/SingleFile) addon can fix such bug by the following:
If the file name of a saved page looks like "56833935-156b-4d8c-a00f-19599c6513d3.html", disable the option "Misc > save pages in background". Reinstalling the browser may also fix this issue. You can find more info about this bug here. This bug has been closed by Google as "WontFix".

I hope MarkDownload addon can have similar configuration.

**Closed** 2021-02-15 06:31 UTC
Labels: bug

**Comment by cdpath** [comment] 2022-09-14 08:57
For those who found this issue and still having hashed filename, just go to Options > Download Mode > Choose **Content Link**.  It will give you correct filename, at the cost of downloading images been disabled.
