### ISSUE TITLE
[Feature Request] Links to anchor in same document exported as markdown internal links

### ISSUE THREAD

**Issue by joserprieto** [deathau/markdownload#130] opened 2022-03-04 21:41 UTC
The current behaviour, if you have a TOC or similar, with links to an anchor on the same URL, in the exported markdown is generated as a link to the original base URL, not at the current markdown.

For example; for the YAML spec:

[YAML Ain’t Markup Language (YAML™) version 1.2 Revision 1.2.2 (2021-10-01)](https://yaml.org/spec/1.2.2/) 

You can see the "Contents" paragraf, with internal links like this:

Contents

```plain
Chapter 1. Introduction to YAML
1.1. Goals
1.2. YAML History
1.3. Terminology
```

```html
<p><strong>Contents</strong></p>
<ul id="markdown-toc">
  <li><a href="#yaml-aint-markup-language-yaml-version-12" id="markdown-toc-yaml-aint-markup-language-yaml-version-12">YAML Ain’t Markup Language (YAML™) version 1.2</a>    <ul>
      <li><a href="#revision-122-2021-10-01" id="markdown-toc-revision-122-2021-10-01">Revision 1.2.2 (2021-10-01)</a></li>
    </ul>
  </li>
  <li><a href="#chapter-1-introduction-to-yaml" id="markdown-toc-chapter-1-introduction-to-yaml">Chapter 1. Introduction to YAML</a>    <ul>
      <li><a href="#11-goals" id="markdown-toc-11-goals">1.1. Goals</a></li>
      <li><a href="#12-yaml-history" id="markdown-toc-12-yaml-history">1.2. YAML History</a></li>
      <li><a href="#13-terminology" id="markdown-toc-13-terminology">1.3. Terminology</a></li>
    </ul>
  </li>
<!-- ... -->
```

The chrome extensions outputs something like this:

```markdown
[Chapter 1. Introduction to YAML](https://yaml.org/spec/1.2.2/#chapter-1-introduction-to-yaml)
[1.1. Goals](https://yaml.org/spec/1.2.2/#11-goals)
[1.2. YAML History](https://yaml.org/spec/1.2.2/#12-yaml-history)
[1.3. Terminology](https://yaml.org/spec/1.2.2/#13-terminology)
```

**But**, if you want to save the export, for example, on obsidian, these export has links outside the same note / document.

An approach to solve this, it's put a named anchor on markdown, as in spec (some references):

- https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown
- https://dev.to/stephencweiss/named-anchors-markdown-2hm5
- https://maksimivanov.com/posts/named-anchor-markdown/

On Obsidian, this approach not work; but, if you put a reference to the same document (as if it will be a cross reference), it will work:

On this article:

https://www.guru99.com/smoke-testing.html

I exported it to markdown, and change the links of the TOC, as you can show follow (the filename is: "What is Smoke Testing - How to do with EXAMPLES")

```markdown
## Smoke Testing

...

- [[What is Smoke Testing - How to do with EXAMPLES#Smoke Testing|What is Smoke Testing?]]

- [[What is Smoke Testing - How to do with EXAMPLES#When do we do smoke testing|When do we do smoke testing]]

...

## When do we do smoke testing

  

Smoke Testing is done whenever the new functionalities of software are developed and integrated with existing build that is deployed in QA/staging environment. It ensures that all critical functionalities are working correctly or not.
```

So, the ideal approach will can be that this can be an option of the export.

Many thanks, and very good job!

**Comment by deathau** [comment] 2022-12-01 04:49
duplicate of #70 (though this one has more info)

**Closed by deathau** 2022-12-01 04:49 UTC
